# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [10]:
import numpy as np
a=np.zeros(100)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [7]:
a=np.ones(100)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [20]:
a=np.full(100,3)
print(a)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Поменять 2 строки в матрице

In [14]:
a=np.arange(16).reshape(4,4)
print(a)
a[[1,2]] = a[[2,1]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [12 13 14 15]]


#### 5. Создать вектор со значениями от 10 до 100

In [19]:
a=np.arange(start=10,stop=101,step=1)
print(a)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [16]:
a=np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Создать 3x3 единичную матрицу

In [17]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Создать массив 3x3x3 со случайными значениями

In [18]:
a=np.random.random((3,3,3))
print(a)

[[[0.88472767 0.63726951 0.39838795]
  [0.5910884  0.2148429  0.39317175]
  [0.05194193 0.14511574 0.85718119]]

 [[0.80624848 0.27144111 0.54965046]
  [0.82480039 0.73139461 0.90714055]
  [0.27966019 0.43236707 0.7292419 ]]

 [[0.68170108 0.96230377 0.80951708]
  [0.62216986 0.77873431 0.00889713]
  [0.92338152 0.14930613 0.1886706 ]]]


#### 9. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [25]:
a=np.random.random((10,10))
amin,amax=a.min(),a.max()
print(a)
print(amin,amax)

[[0.12757756 0.81407521 0.55909613 0.28802537 0.21234487 0.35426426
  0.68072642 0.94156534 0.00391103 0.23618278]
 [0.85055659 0.76292983 0.07460241 0.15639492 0.22466145 0.3470632
  0.46920768 0.79316504 0.79153136 0.22041373]
 [0.34697076 0.62623016 0.27841999 0.69018077 0.07953771 0.71652856
  0.81485385 0.83726493 0.19796249 0.91583192]
 [0.73061156 0.91332437 0.97043978 0.09091527 0.32851223 0.2233626
  0.94155602 0.95423884 0.91240544 0.92810509]
 [0.18590487 0.04436916 0.53956339 0.63792103 0.21301753 0.46861523
  0.2901088  0.27567997 0.17363749 0.89711724]
 [0.69233682 0.87345907 0.45369514 0.44902622 0.46594008 0.30133419
  0.28251409 0.33481605 0.71402779 0.40946505]
 [0.5960424  0.96359731 0.1967604  0.21653049 0.75836735 0.10012365
  0.95589607 0.54860866 0.18518841 0.80011114]
 [0.47970006 0.71500557 0.22483674 0.50344659 0.33549698 0.11993206
  0.67536447 0.52597355 0.50646358 0.47936352]
 [0.07332231 0.97860244 0.28399506 0.65191126 0.78609113 0.35479819
  0.76650089 0

#### 10. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [29]:
a=np.random.random(30)
m=a.mean()
print(a)
print(m)

[0.5754414  0.89531315 0.66719561 0.21790349 0.85691926 0.3798199
 0.17190577 0.03543786 0.58883896 0.9845236  0.8529351  0.94633418
 0.52622949 0.80371314 0.51351325 0.6604369  0.64158398 0.67131218
 0.75762554 0.83021419 0.79170429 0.92981454 0.59401782 0.75940035
 0.54698676 0.75513276 0.850198   0.24135382 0.60791591 0.39288669]
0.6348869292921417


#### 11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [30]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 12. Перемножить матрицы 5x3 и 3x2

In [31]:
a=np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 13. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [32]:
a=np.arange(16)
print(a)
a[(3<a)&(a<=8)]*=-1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15]


#### 14. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [35]:
a=np.zeros((5,5))
a+=np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 15. Отнять среднее из каждой строки в матрице

In [39]:
a=np.random.random((4,4))
print(a)
b=a-a.mean(axis=1,keepdims=True)
print(b)

[[0.81386975 0.52479037 0.1548526  0.8033592 ]
 [0.50198106 0.32978172 0.87353099 0.75025704]
 [0.47138314 0.85382073 0.20691853 0.97511376]
 [0.03249978 0.19291692 0.84661875 0.11366289]]
[[ 0.23965177 -0.04942761 -0.41936538  0.22914122]
 [-0.11190664 -0.28410599  0.25964329  0.13636934]
 [-0.1554259   0.22701169 -0.41989051  0.34830472]
 [-0.2639248  -0.10350767  0.55019416 -0.18276169]]
